#Development (vite)
# Base image
FROM node:20-alpine

# Working directory inside container
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Expose Vite dev server port
EXPOSE 5173

# Start Vite in dev mode, accessible from outside container
CMD ["npm", "run", "dev", "--", "--host"]

