services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: commoncare-backend
    env_file:
      - .env
    environment:
      SECRET_KEY: docker-secret-key
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: on-failure
